// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.22.4
// source: game.proto

package message

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Point3F struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X float32 `protobuf:"fixed32,1,opt,name=X,proto3" json:"X,omitempty"`
	Y float32 `protobuf:"fixed32,2,opt,name=Y,proto3" json:"Y,omitempty"`
	Z float32 `protobuf:"fixed32,3,opt,name=Z,proto3" json:"Z,omitempty"`
}

func (x *Point3F) Reset() {
	*x = Point3F{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Point3F) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Point3F) ProtoMessage() {}

func (x *Point3F) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Point3F.ProtoReflect.Descriptor instead.
func (*Point3F) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{0}
}

func (x *Point3F) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Point3F) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Point3F) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

type C_Z_Move struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PacketHead *IPacket       `protobuf:"bytes,1,opt,name=PacketHead,proto3" json:"PacketHead,omitempty"`
	Move       *C_Z_Move_Move `protobuf:"bytes,2,opt,name=move,proto3" json:"move,omitempty"`
}

func (x *C_Z_Move) Reset() {
	*x = C_Z_Move{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C_Z_Move) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C_Z_Move) ProtoMessage() {}

func (x *C_Z_Move) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C_Z_Move.ProtoReflect.Descriptor instead.
func (*C_Z_Move) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{1}
}

func (x *C_Z_Move) GetPacketHead() *IPacket {
	if x != nil {
		return x.PacketHead
	}
	return nil
}

func (x *C_Z_Move) GetMove() *C_Z_Move_Move {
	if x != nil {
		return x.Move
	}
	return nil
}

// skill
type C_Z_Skill struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PacketHead *IPacket `protobuf:"bytes,1,opt,name=PacketHead,proto3" json:"PacketHead,omitempty"`
	SkillId    int32    `protobuf:"varint,2,opt,name=SkillId,proto3" json:"SkillId,omitempty"`
	TargetId   int64    `protobuf:"varint,3,opt,name=TargetId,proto3" json:"TargetId,omitempty"`
}

func (x *C_Z_Skill) Reset() {
	*x = C_Z_Skill{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C_Z_Skill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C_Z_Skill) ProtoMessage() {}

func (x *C_Z_Skill) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C_Z_Skill.ProtoReflect.Descriptor instead.
func (*C_Z_Skill) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{2}
}

func (x *C_Z_Skill) GetPacketHead() *IPacket {
	if x != nil {
		return x.PacketHead
	}
	return nil
}

func (x *C_Z_Skill) GetSkillId() int32 {
	if x != nil {
		return x.SkillId
	}
	return 0
}

func (x *C_Z_Skill) GetTargetId() int64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

type Z_C_LoginMap struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PacketHead *IPacket `protobuf:"bytes,1,opt,name=PacketHead,proto3" json:"PacketHead,omitempty"`
	Id         int64    `protobuf:"varint,2,opt,name=Id,proto3" json:"Id,omitempty"`
	Pos        *Point3F `protobuf:"bytes,3,opt,name=Pos,proto3" json:"Pos,omitempty"`
	Rotation   float32  `protobuf:"fixed32,4,opt,name=Rotation,proto3" json:"Rotation,omitempty"`
}

func (x *Z_C_LoginMap) Reset() {
	*x = Z_C_LoginMap{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Z_C_LoginMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Z_C_LoginMap) ProtoMessage() {}

func (x *Z_C_LoginMap) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Z_C_LoginMap.ProtoReflect.Descriptor instead.
func (*Z_C_LoginMap) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{3}
}

func (x *Z_C_LoginMap) GetPacketHead() *IPacket {
	if x != nil {
		return x.PacketHead
	}
	return nil
}

func (x *Z_C_LoginMap) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Z_C_LoginMap) GetPos() *Point3F {
	if x != nil {
		return x.Pos
	}
	return nil
}

func (x *Z_C_LoginMap) GetRotation() float32 {
	if x != nil {
		return x.Rotation
	}
	return 0
}

type Z_C_ENTITY struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PacketHead *IPacket             `protobuf:"bytes,1,opt,name=PacketHead,proto3" json:"PacketHead,omitempty"`
	EntityInfo []*Z_C_ENTITY_Entity `protobuf:"bytes,2,rep,name=EntityInfo,proto3" json:"EntityInfo,omitempty"`
}

func (x *Z_C_ENTITY) Reset() {
	*x = Z_C_ENTITY{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Z_C_ENTITY) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Z_C_ENTITY) ProtoMessage() {}

func (x *Z_C_ENTITY) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Z_C_ENTITY.ProtoReflect.Descriptor instead.
func (*Z_C_ENTITY) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{4}
}

func (x *Z_C_ENTITY) GetPacketHead() *IPacket {
	if x != nil {
		return x.PacketHead
	}
	return nil
}

func (x *Z_C_ENTITY) GetEntityInfo() []*Z_C_ENTITY_Entity {
	if x != nil {
		return x.EntityInfo
	}
	return nil
}

type C_Z_Move_Move struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mode   int32                 `protobuf:"varint,1,opt,name=Mode,proto3" json:"Mode,omitempty"`
	Normal *C_Z_Move_Move_Normal `protobuf:"bytes,2,opt,name=normal,proto3" json:"normal,omitempty"`
}

func (x *C_Z_Move_Move) Reset() {
	*x = C_Z_Move_Move{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C_Z_Move_Move) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C_Z_Move_Move) ProtoMessage() {}

func (x *C_Z_Move_Move) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C_Z_Move_Move.ProtoReflect.Descriptor instead.
func (*C_Z_Move_Move) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{1, 0}
}

func (x *C_Z_Move_Move) GetMode() int32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *C_Z_Move_Move) GetNormal() *C_Z_Move_Move_Normal {
	if x != nil {
		return x.Normal
	}
	return nil
}

type C_Z_Move_Move_Normal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pos      *Point3F `protobuf:"bytes,1,opt,name=Pos,proto3" json:"Pos,omitempty"`
	Yaw      float32  `protobuf:"fixed32,2,opt,name=Yaw,proto3" json:"Yaw,omitempty"`
	Duration float32  `protobuf:"fixed32,3,opt,name=Duration,proto3" json:"Duration,omitempty"`
}

func (x *C_Z_Move_Move_Normal) Reset() {
	*x = C_Z_Move_Move_Normal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C_Z_Move_Move_Normal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C_Z_Move_Move_Normal) ProtoMessage() {}

func (x *C_Z_Move_Move_Normal) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C_Z_Move_Move_Normal.ProtoReflect.Descriptor instead.
func (*C_Z_Move_Move_Normal) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{1, 0, 0}
}

func (x *C_Z_Move_Move_Normal) GetPos() *Point3F {
	if x != nil {
		return x.Pos
	}
	return nil
}

func (x *C_Z_Move_Move_Normal) GetYaw() float32 {
	if x != nil {
		return x.Yaw
	}
	return 0
}

func (x *C_Z_Move_Move_Normal) GetDuration() float32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

type Z_C_ENTITY_Entity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    int64                        `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Move  *Z_C_ENTITY_Entity_MoveMask  `protobuf:"bytes,2,opt,name=Move,proto3" json:"Move,omitempty"`
	Stats *Z_C_ENTITY_Entity_StatsMask `protobuf:"bytes,3,opt,name=Stats,proto3" json:"Stats,omitempty"`
}

func (x *Z_C_ENTITY_Entity) Reset() {
	*x = Z_C_ENTITY_Entity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Z_C_ENTITY_Entity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Z_C_ENTITY_Entity) ProtoMessage() {}

func (x *Z_C_ENTITY_Entity) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Z_C_ENTITY_Entity.ProtoReflect.Descriptor instead.
func (*Z_C_ENTITY_Entity) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{4, 0}
}

func (x *Z_C_ENTITY_Entity) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Z_C_ENTITY_Entity) GetMove() *Z_C_ENTITY_Entity_MoveMask {
	if x != nil {
		return x.Move
	}
	return nil
}

func (x *Z_C_ENTITY_Entity) GetStats() *Z_C_ENTITY_Entity_StatsMask {
	if x != nil {
		return x.Stats
	}
	return nil
}

type Z_C_ENTITY_Entity_MoveMask struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pos             *Point3F `protobuf:"bytes,1,opt,name=Pos,proto3" json:"Pos,omitempty"`
	Rotation        float32  `protobuf:"fixed32,2,opt,name=Rotation,proto3" json:"Rotation,omitempty"`
	ForceUpdateFlag bool     `protobuf:"varint,3,opt,name=ForceUpdateFlag,proto3" json:"ForceUpdateFlag,omitempty"`
}

func (x *Z_C_ENTITY_Entity_MoveMask) Reset() {
	*x = Z_C_ENTITY_Entity_MoveMask{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Z_C_ENTITY_Entity_MoveMask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Z_C_ENTITY_Entity_MoveMask) ProtoMessage() {}

func (x *Z_C_ENTITY_Entity_MoveMask) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Z_C_ENTITY_Entity_MoveMask.ProtoReflect.Descriptor instead.
func (*Z_C_ENTITY_Entity_MoveMask) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{4, 0, 0}
}

func (x *Z_C_ENTITY_Entity_MoveMask) GetPos() *Point3F {
	if x != nil {
		return x.Pos
	}
	return nil
}

func (x *Z_C_ENTITY_Entity_MoveMask) GetRotation() float32 {
	if x != nil {
		return x.Rotation
	}
	return 0
}

func (x *Z_C_ENTITY_Entity_MoveMask) GetForceUpdateFlag() bool {
	if x != nil {
		return x.ForceUpdateFlag
	}
	return false
}

type Z_C_ENTITY_Entity_StatsMask struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HP    int32 `protobuf:"varint,1,opt,name=HP,proto3" json:"HP,omitempty"`
	MP    int32 `protobuf:"varint,2,opt,name=MP,proto3" json:"MP,omitempty"`
	MaxHP int32 `protobuf:"varint,3,opt,name=MaxHP,proto3" json:"MaxHP,omitempty"`
	MaxMP int32 `protobuf:"varint,4,opt,name=MaxMP,proto3" json:"MaxMP,omitempty"`
}

func (x *Z_C_ENTITY_Entity_StatsMask) Reset() {
	*x = Z_C_ENTITY_Entity_StatsMask{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Z_C_ENTITY_Entity_StatsMask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Z_C_ENTITY_Entity_StatsMask) ProtoMessage() {}

func (x *Z_C_ENTITY_Entity_StatsMask) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Z_C_ENTITY_Entity_StatsMask.ProtoReflect.Descriptor instead.
func (*Z_C_ENTITY_Entity_StatsMask) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{4, 0, 1}
}

func (x *Z_C_ENTITY_Entity_StatsMask) GetHP() int32 {
	if x != nil {
		return x.HP
	}
	return 0
}

func (x *Z_C_ENTITY_Entity_StatsMask) GetMP() int32 {
	if x != nil {
		return x.MP
	}
	return 0
}

func (x *Z_C_ENTITY_Entity_StatsMask) GetMaxHP() int32 {
	if x != nil {
		return x.MaxHP
	}
	return 0
}

func (x *Z_C_ENTITY_Entity_StatsMask) GetMaxMP() int32 {
	if x != nil {
		return x.MaxMP
	}
	return 0
}

var File_game_proto protoreflect.FileDescriptor

var file_game_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0d, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x33, 0x0a, 0x07, 0x50,
	0x6f, 0x69, 0x6e, 0x74, 0x33, 0x46, 0x12, 0x0c, 0x0a, 0x01, 0x58, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x01, 0x58, 0x12, 0x0c, 0x0a, 0x01, 0x59, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x01, 0x59, 0x12, 0x0c, 0x0a, 0x01, 0x5a, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x5a,
	0x22, 0xf8, 0x01, 0x0a, 0x08, 0x43, 0x5f, 0x5a, 0x5f, 0x4d, 0x6f, 0x76, 0x65, 0x12, 0x28, 0x0a,
	0x0a, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x48, 0x65, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x08, 0x2e, 0x49, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x0a, 0x50, 0x61, 0x63,
	0x6b, 0x65, 0x74, 0x48, 0x65, 0x61, 0x64, 0x12, 0x22, 0x0a, 0x04, 0x6d, 0x6f, 0x76, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x43, 0x5f, 0x5a, 0x5f, 0x4d, 0x6f, 0x76, 0x65,
	0x2e, 0x4d, 0x6f, 0x76, 0x65, 0x52, 0x04, 0x6d, 0x6f, 0x76, 0x65, 0x1a, 0x9d, 0x01, 0x0a, 0x04,
	0x4d, 0x6f, 0x76, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x4d, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x4d, 0x6f, 0x64, 0x65, 0x12, 0x2d, 0x0a, 0x06, 0x6e, 0x6f, 0x72, 0x6d,
	0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x43, 0x5f, 0x5a, 0x5f, 0x4d,
	0x6f, 0x76, 0x65, 0x2e, 0x4d, 0x6f, 0x76, 0x65, 0x2e, 0x4e, 0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x52,
	0x06, 0x6e, 0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x1a, 0x52, 0x0a, 0x06, 0x4e, 0x6f, 0x72, 0x6d, 0x61,
	0x6c, 0x12, 0x1a, 0x0a, 0x03, 0x50, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08,
	0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x33, 0x46, 0x52, 0x03, 0x50, 0x6f, 0x73, 0x12, 0x10, 0x0a,
	0x03, 0x59, 0x61, 0x77, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x59, 0x61, 0x77, 0x12,
	0x1a, 0x0a, 0x08, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x08, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x6b, 0x0a, 0x09, 0x43,
	0x5f, 0x5a, 0x5f, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x12, 0x28, 0x0a, 0x0a, 0x50, 0x61, 0x63, 0x6b,
	0x65, 0x74, 0x48, 0x65, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x49,
	0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x0a, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x48, 0x65,
	0x61, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x49, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x07, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08,
	0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08,
	0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x49, 0x64, 0x22, 0x80, 0x01, 0x0a, 0x0c, 0x5a, 0x5f, 0x43,
	0x5f, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x4d, 0x61, 0x70, 0x12, 0x28, 0x0a, 0x0a, 0x50, 0x61, 0x63,
	0x6b, 0x65, 0x74, 0x48, 0x65, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e,
	0x49, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x0a, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x48,
	0x65, 0x61, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x02, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x03, 0x50, 0x6f, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x08, 0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x33, 0x46, 0x52, 0x03, 0x50, 0x6f, 0x73, 0x12,
	0x1a, 0x0a, 0x08, 0x52, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x08, 0x52, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0xb1, 0x03, 0x0a, 0x0a,
	0x5a, 0x5f, 0x43, 0x5f, 0x45, 0x4e, 0x54, 0x49, 0x54, 0x59, 0x12, 0x28, 0x0a, 0x0a, 0x50, 0x61,
	0x63, 0x6b, 0x65, 0x74, 0x48, 0x65, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08,
	0x2e, 0x49, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x0a, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74,
	0x48, 0x65, 0x61, 0x64, 0x12, 0x32, 0x0a, 0x0a, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x49, 0x6e,
	0x66, 0x6f, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x5a, 0x5f, 0x43, 0x5f, 0x45,
	0x4e, 0x54, 0x49, 0x54, 0x59, 0x2e, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x0a, 0x45, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x1a, 0xc4, 0x02, 0x0a, 0x06, 0x45, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x02, 0x49, 0x64, 0x12, 0x2f, 0x0a, 0x04, 0x4d, 0x6f, 0x76, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1b, 0x2e, 0x5a, 0x5f, 0x43, 0x5f, 0x45, 0x4e, 0x54, 0x49, 0x54, 0x59, 0x2e, 0x45,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x4d, 0x6f, 0x76, 0x65, 0x4d, 0x61, 0x73, 0x6b, 0x52, 0x04,
	0x4d, 0x6f, 0x76, 0x65, 0x12, 0x32, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x74, 0x73, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x5a, 0x5f, 0x43, 0x5f, 0x45, 0x4e, 0x54, 0x49, 0x54, 0x59,
	0x2e, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x73, 0x4d, 0x61, 0x73,
	0x6b, 0x52, 0x05, 0x53, 0x74, 0x61, 0x74, 0x73, 0x1a, 0x6c, 0x0a, 0x08, 0x4d, 0x6f, 0x76, 0x65,
	0x4d, 0x61, 0x73, 0x6b, 0x12, 0x1a, 0x0a, 0x03, 0x50, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x08, 0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x33, 0x46, 0x52, 0x03, 0x50, 0x6f, 0x73,
	0x12, 0x1a, 0x0a, 0x08, 0x52, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x08, 0x52, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x28, 0x0a, 0x0f,
	0x46, 0x6f, 0x72, 0x63, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x46, 0x6c, 0x61, 0x67, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0f, 0x46, 0x6f, 0x72, 0x63, 0x65, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x46, 0x6c, 0x61, 0x67, 0x1a, 0x57, 0x0a, 0x09, 0x53, 0x74, 0x61, 0x74, 0x73, 0x4d,
	0x61, 0x73, 0x6b, 0x12, 0x0e, 0x0a, 0x02, 0x48, 0x50, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x02, 0x48, 0x50, 0x12, 0x0e, 0x0a, 0x02, 0x4d, 0x50, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x02, 0x4d, 0x50, 0x12, 0x14, 0x0a, 0x05, 0x4d, 0x61, 0x78, 0x48, 0x50, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x4d, 0x61, 0x78, 0x48, 0x50, 0x12, 0x14, 0x0a, 0x05, 0x4d, 0x61, 0x78,
	0x4d, 0x50, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x4d, 0x61, 0x78, 0x4d, 0x50, 0x42,
	0x0b, 0x5a, 0x09, 0x2f, 0x3b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_game_proto_rawDescOnce sync.Once
	file_game_proto_rawDescData = file_game_proto_rawDesc
)

func file_game_proto_rawDescGZIP() []byte {
	file_game_proto_rawDescOnce.Do(func() {
		file_game_proto_rawDescData = protoimpl.X.CompressGZIP(file_game_proto_rawDescData)
	})
	return file_game_proto_rawDescData
}

var file_game_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_game_proto_goTypes = []interface{}{
	(*Point3F)(nil),                     // 0: Point3F
	(*C_Z_Move)(nil),                    // 1: C_Z_Move
	(*C_Z_Skill)(nil),                   // 2: C_Z_Skill
	(*Z_C_LoginMap)(nil),                // 3: Z_C_LoginMap
	(*Z_C_ENTITY)(nil),                  // 4: Z_C_ENTITY
	(*C_Z_Move_Move)(nil),               // 5: C_Z_Move.Move
	(*C_Z_Move_Move_Normal)(nil),        // 6: C_Z_Move.Move.Normal
	(*Z_C_ENTITY_Entity)(nil),           // 7: Z_C_ENTITY.Entity
	(*Z_C_ENTITY_Entity_MoveMask)(nil),  // 8: Z_C_ENTITY.Entity.MoveMask
	(*Z_C_ENTITY_Entity_StatsMask)(nil), // 9: Z_C_ENTITY.Entity.StatsMask
	(*IPacket)(nil),                     // 10: IPacket
}
var file_game_proto_depIdxs = []int32{
	10, // 0: C_Z_Move.PacketHead:type_name -> IPacket
	5,  // 1: C_Z_Move.move:type_name -> C_Z_Move.Move
	10, // 2: C_Z_Skill.PacketHead:type_name -> IPacket
	10, // 3: Z_C_LoginMap.PacketHead:type_name -> IPacket
	0,  // 4: Z_C_LoginMap.Pos:type_name -> Point3F
	10, // 5: Z_C_ENTITY.PacketHead:type_name -> IPacket
	7,  // 6: Z_C_ENTITY.EntityInfo:type_name -> Z_C_ENTITY.Entity
	6,  // 7: C_Z_Move.Move.normal:type_name -> C_Z_Move.Move.Normal
	0,  // 8: C_Z_Move.Move.Normal.Pos:type_name -> Point3F
	8,  // 9: Z_C_ENTITY.Entity.Move:type_name -> Z_C_ENTITY.Entity.MoveMask
	9,  // 10: Z_C_ENTITY.Entity.Stats:type_name -> Z_C_ENTITY.Entity.StatsMask
	0,  // 11: Z_C_ENTITY.Entity.MoveMask.Pos:type_name -> Point3F
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_game_proto_init() }
func file_game_proto_init() {
	if File_game_proto != nil {
		return
	}
	file_message_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_game_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Point3F); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C_Z_Move); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C_Z_Skill); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Z_C_LoginMap); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Z_C_ENTITY); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C_Z_Move_Move); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C_Z_Move_Move_Normal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Z_C_ENTITY_Entity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Z_C_ENTITY_Entity_MoveMask); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Z_C_ENTITY_Entity_StatsMask); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_game_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_game_proto_goTypes,
		DependencyIndexes: file_game_proto_depIdxs,
		MessageInfos:      file_game_proto_msgTypes,
	}.Build()
	File_game_proto = out.File
	file_game_proto_rawDesc = nil
	file_game_proto_goTypes = nil
	file_game_proto_depIdxs = nil
}
